# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/embed.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/embed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsrc/embed.proto\x12\x05\x65mbed\"\x1c\n\x0c\x45mbedRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\xb0\x01\n\rEmbedResponse\x12+\n\x06status\x18\x01 \x01(\x0e\x32\x1b.embed.EmbedResponse.Status\x12\"\n\x05\x65mbed\x18\x02 \x01(\x0b\x32\x11.embed.EmbedValueH\x00\x12\x0f\n\x05\x65rror\x18\x03 \x01(\tH\x00\"2\n\x06Status\x12\x0e\n\nINCOMPLETE\x10\x00\x12\x0c\n\x08\x43OMPLETE\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x42\t\n\x07payload\"\x1c\n\nEmbedValue\x12\x0e\n\x06values\x18\x01 \x03(\x02\x32\x45\n\x0c\x45mbedService\x12\x35\n\x08GetEmbed\x12\x13.embed.EmbedRequest\x1a\x14.embed.EmbedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.embed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDREQUEST']._serialized_start=26
  _globals['_EMBEDREQUEST']._serialized_end=54
  _globals['_EMBEDRESPONSE']._serialized_start=57
  _globals['_EMBEDRESPONSE']._serialized_end=233
  _globals['_EMBEDRESPONSE_STATUS']._serialized_start=172
  _globals['_EMBEDRESPONSE_STATUS']._serialized_end=222
  _globals['_EMBEDVALUE']._serialized_start=235
  _globals['_EMBEDVALUE']._serialized_end=263
  _globals['_EMBEDSERVICE']._serialized_start=265
  _globals['_EMBEDSERVICE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
